-- Create a table
CREATE TABLE Passengers (
    PassengerID INT PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(50),
    Age INT,
    DepartureCity VARCHAR(50),
    ArrivalCity VARCHAR(50)
);


-- Data Insertion

INSERT INTO Passengers (Name, Age, DepartureCity, ArrivalCity) VALUES
('Alice', 25, 'New York', 'Los Angeles'),
('Bob', 30, 'London', 'Paris'),
('Emily', 28, 'Sydney', 'Tokyo'),
('Daniel', 35, 'Beijing', 'Shanghai'),
('Olivia', 22, 'Toronto', 'Vancouver'),
('Ava', 31, 'Miami', 'Orlando'),
('Isaac', 40, 'Chicago', 'Houston'),
('Eleanor', 27, 'Madrid', 'Barcelona'),
('Austin', 29, 'Dallas', 'Austin'),
('Isabella', 26, 'Rome', 'Milan'),
('Sophia', 23, 'Berlin', 'Munich'),
('Liam', 32, 'Sydney', 'Melbourne'),
('Charlotte', 29, 'Paris', 'Rome'),
('Noah', 33, 'Los Angeles', 'San Francisco'),
('Amelia', 26, 'London', 'Edinburgh'),
('Ethan', 30, 'Tokyo', 'Osaka'),
('Harper', 28, 'Toronto', 'Montreal'),
('Mason', 34, 'Chicago', 'Atlanta'),
('Evelyn', 27, 'Madrid', 'Lisbon'),
('Benjamin', 31, 'New York', 'Washington D.C.'),
('Mia', 24, 'Barcelona', 'Valencia'),
('Alexander', 35, 'Houston', 'Dallas'),
('Abigail', 25, 'Miami', 'Tampa'),
('James', 36, 'Sydney', 'Brisbane'),
('Scarlett', 30, 'Paris', 'Lyon'),
('Logan', 37, 'Los Angeles', 'Las Vegas'),
('Lily', 31, 'London', 'Dublin'),
('Elijah', 38, 'Tokyo', 'Kyoto'),
('Aria', 32, 'Toronto', 'Ottawa'),
('Oliver', 39, 'Chicago', 'Detroit'),
('Grace', 33, 'Madrid', 'Seville'),
('William', 40, 'New York', 'Philadelphia'),
('Zoey', 34, 'Barcelona', 'Malaga'),
('Michael', 41, 'Houston', 'San Antonio'),
('Nora', 35, 'Miami', 'Fort Lauderdale'),
('Jack', 42, 'Sydney', 'Adelaide'),
('Penelope', 36, 'Paris', 'Marseille'),
('Lucas', 43, 'Los Angeles', 'San Diego'),
('Hannah', 37, 'London', 'Manchester'),
('Henry', 44, 'Tokyo', 'Nagoya'),
('Elizabeth', 38, 'Toronto', 'Quebec City'),
('Jacob', 45, 'Chicago', 'Minneapolis'),
('Avery', 39, 'Madrid', 'Valencia'),
('Alexander', 46, 'New York', 'Boston'),
('Ella', 40, 'Barcelona', 'Madrid'),
('Matthew', 47, 'Houston', 'Austin'),
('Addison', 41, 'Miami', 'Jacksonville'),
('Sebastian', 48, 'Sydney', 'Perth'),
('Ellie', 42, 'Paris', 'Bordeaux'),
('Daniel', 49, 'Los Angeles', 'Portland'),
('Victoria', 43, 'London', 'Glasgow'),
('Andrew', 50, 'Tokyo', 'Hiroshima'),
('Mila', 44, 'Toronto', 'Vancouver'),
('David', 51, 'Chicago', 'St. Louis'),
('Avery', 45, 'Madrid', 'Bilbao'),
('Joseph', 52, 'New York', 'Chicago'),
('Luna', 46, 'Barcelona', 'Ibiza'),
('Ethan', 53, 'Houston', 'San Francisco'),
('Leah', 47, 'Miami', 'Key West'),
('Jackson', 54, 'Sydney', 'Brisbane'),
('Layla', 48, 'Paris', 'Nice'),
('Gabriel', 55, 'Los Angeles', 'Las Vegas'),
('Nora', 49, 'London', 'Dublin'),
('Christopher', 56, 'Tokyo', 'Osaka'),
('Harper', 50, 'Toronto', 'Ottawa'),
('Ava', 57, 'Chicago', 'Detroit'),
('Eleanor', 51, 'Madrid', 'Seville'),
('Benjamin', 58, 'New York', 'Philadelphia'),
('Stella', 52, 'Barcelona', 'Malaga'),
('Samuel', 59, 'Houston', 'San Antonio'),
('Clara', 53, 'Miami', 'Fort Lauderdale'),
('William', 60, 'Sydney', 'Adelaide'),
('Grace', 54, 'Paris', 'Marseille'),
('Logan', 61, 'Los Angeles', 'San Diego'),
('Penelope', 55, 'London', 'Manchester'),
('Elijah', 62, 'Tokyo', 'Nagoya'),
('Scarlett', 56, 'Toronto', 'Quebec City'),
('Oliver', 63, 'Chicago', 'Minneapolis'),
('Mia', 57, 'Madrid', 'Valencia'),
('Aiden', 64, 'New York', 'Boston'),
('Zoey', 58, 'Barcelona', 'Madrid'),
('Carter', 65, 'Houston', 'Austin'),
('Sofia', 59, 'Miami', 'Jacksonville'),
('Ethan', 66, 'Sydney', 'Perth'),
('Chloe', 60, 'Paris', 'Bordeaux'),
('Jackson', 67, 'Los Angeles', 'Portland'),
('Emily', 61, 'London', 'Glasgow'),
('Mason', 68, 'Tokyo', 'Hiroshima'),
('Harper', 62, 'Toronto', 'Vancouver'),
('Lucas', 69, 'Chicago', 'St. Louis'),
('Abigail', 63, 'Madrid', 'Bilbao'),
('Noah', 70, 'New York', 'Chicago'),
('Amelia', 64, 'Barcelona', 'Ibiza'),
('Michael', 71, 'Houston', 'San Francisco'),
('Evelyn', 65, 'Miami', 'Key West'),
('Liam', 72, 'Sydney', 'Brisbane'),
('Charlotte', 66, 'Paris', 'Nice'),
('Daniel', 73, 'Los Angeles', 'Las Vegas'),
('Isabella', 67, 'London', 'Dublin'),
('Alexander', 74, 'Tokyo', 'Osaka'),
('Ava', 68, 'Toronto', 'Ottawa'),
('Benjamin', 75, 'Chicago', 'Detroit'),
('Emily', 69, 'Madrid', 'Seville'),
('Mia', 76, 'New York', 'Philadelphia'),
('Oliver', 70, 'Barcelona', 'Malaga'),
('Sophia', 77, 'Houston', 'San Antonio'),
('Harper', 71, 'Miami', 'Fort Lauderdale'),
('Noah', 78, 'Sydney', 'Adelaide'),
('Amelia', 72, 'Paris', 'Marseille'),
('Liam', 79, 'Los Angeles', 'San Diego'),
('Charlotte', 73, 'London', 'Manchester'),
('Ethan', 80, 'Tokyo', 'Nagoya'),
('Evelyn', 74, 'Toronto', 'Quebec City'),
('Mason', 81, 'Chicago', 'Minneapolis'),
('Harper', 75, 'Madrid', 'Valencia'),
('William', 82, 'New York', 'Boston'),
('Mia', 76, 'Barcelona', 'Madrid'),
('Michael', 83, 'Houston', 'Austin'),
('Emily', 77, 'Miami', 'Jacksonville'),
('Alexander', 84, 'Sydney', 'Perth'),
('Ava', 78, 'Paris', 'Bordeaux'),
('Benjamin', 85, 'Los Angeles', 'Portland'),
('Charlotte', 79, 'London', 'Glasgow'),
('Daniel', 86, 'Tokyo', 'Hiroshima'),
('Isabella', 80, 'Toronto', 'Vancouver'),
('Liam', 87, 'Chicago', 'St. Louis'),
('Emily', 81, 'Madrid', 'Bilbao'),
('Sophia', 88, 'New York', 'Chicago'),
('Harper', 82, 'Barcelona', 'Ibiza'),
('Noah', 89, 'Houston', 'San Francisco'),
('Amelia', 83, 'Miami', 'Key West'),
('Oliver', 90, 'Sydney', 'Brisbane'),
('Charlotte', 84, 'Paris', 'Nice'),
('Ethan', 91, 'Los Angeles', 'Las Vegas'),
('Evelyn', 85, 'London', 'Dublin'),
('Mason', 92, 'Tokyo', 'Osaka'),
('Harper', 86, 'Toronto', 'Ottawa'),
('William', 93, 'Chicago', 'Detroit'),
('Mia', 87, 'Madrid', 'Seville'),
('Michael', 94, 'New York', 'Philadelphia'),
('Emily', 88, 'Barcelona', 'Malaga'),
('Ava', 95, 'Houston', 'San Antonio'),
('Benjamin', 89, 'Miami', 'Fort Lauderdale'),
('Charlotte', 96, 'Sydney', 'Adelaide'),
('Daniel', 90, 'Paris', 'Marseille'),
('Isabella', 97, 'Los Angeles', 'San Diego'),
('Liam', 91, 'London', 'Manchester'),
('Sophia', 98, 'Tokyo', 'Nagoya'),
('Harper', 92, 'Toronto', 'Quebec City'),
('Noah', 99, 'Chicago', 'Minneapolis'),
('Amelia', 93, 'Madrid', 'Valencia'),
('Oliver', 100, 'New York', 'Boston'),
('Charlotte', 94, 'Barcelona', 'Madrid');





---------------------------------------------
----------      version 2        ------------
---------------------------------------------
